### ISSUE TITLE
Support middleware mode

### ISSUE THREAD

**Issue by rtsao** [bluwy/vite-plugin-warmup#7]
When `server: { middlewareMode: true }` is set, `server.httpServer` is null, so this plugin no-ops.

**Comment by bluwy** [comment]
Yeah it's intentionally documented that way currently. It's not safe to do so in `middlewareMode` because we need to wait for Vite to finish setup it's server before we can warmup. Specifically after its [deps optimizer init](https://github.com/vitejs/vite/blob/835249d7351242308dde429003764656a15a6b6e/packages/vite/src/node/server/index.ts#L684-L687).

In non-middleware mode, we can know about that with the listening hook. In middleware mode, there's no way to wait for that. Maybe this could better work if it's built into Vite though.
